# -*- coding: utf-8 -*-
"""gmexico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKxiTfMm2i0q3q-ldDYUzRrBcbu6i2Bf
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

st.title("Probabilidad Bayesiana diaria: GMEXICOB vs Cobre")

ticker_stock = "GMEXICOB.MX"
ticker_copper = "HG=F"

start = st.date_input("Inicio", pd.to_datetime("2024-01-01"))
end = st.date_input("Fin", pd.to_datetime("today"))

window = st.slider("Ventana de cálculo (días)", 30, 252, 120)

# Descargar datos
data = yf.download([ticker_stock, ticker_copper], start=start, end=end)["Close"]
data = data.dropna()

data.columns = ["GMEXICO", "COPPER"]

# Rendimientos
returns = data.pct_change().dropna()

returns["G_up"] = returns["GMEXICO"] > 0
returns["H_up"] = returns["COPPER"] > 0

# Intersección
returns["GH"] = returns["G_up"] & returns["H_up"]

# Rolling probabilities
returns["P_H"] = returns["H_up"].rolling(window).mean()
returns["P_GH"] = returns["GH"].rolling(window).mean()

returns["P_G_given_H"] = returns["P_GH"] / returns["P_H"]

# Probabilidad más reciente
latest_prob = returns["P_G_given_H"].iloc[-1]

st.metric(
    "Probabilidad actual P(GMEXICO sube | Cobre sube)",
    round(latest_prob,3)
)

st.subheader("Evolución de la probabilidad")

st.line_chart(returns["P_G_given_H"])

st.subheader("Precios")

st.line_chart(data.columns = ["COPPER"],data.columns = ["GMEXICO"])

st.subheader("Últimos datos")

st.dataframe(returns.tail())
